Stringtask
rila19/QC_Java pull request #1
Opened 2023-10-01 19:24 UTC by rila19

1. Version / Upload

2023-10-01 20:36 UTC, msalauyou commented on String/Aufgabe3MonthAsString.java
> +    public static void main(String[] args) {
Could you please test it with such dates: 
"03.10.2023"
"03.11.2023"
"03.12.2023"

2023-10-01 20:42 UTC, msalauyou commented on String/Aufgabe4Anagram.java
> +    public static boolean isAnagram(){
Method should accept 2 Strings, in your case it doesn't accept anything. Please re-implement your code to accept 2 strings and do a check.

2023-10-01 20:46 UTC, msalauyou commented on String/Aufgabe5Palindrom.java
> +    public static  void splitStringInArray(){
The name of the method doesn't reflect the action it does. I would name it as `printPolyndroms` or something like that. Also it should accept a String, a sentence which it parses and prints polyndromes.

2023-10-01 20:47 UTC, msalauyou commented on String/AufgabeE.java
> +    public static String Sprint9_Aufgabe(){
please rename the method, should start from lower case, should follow camel case and be a verb that reflects what method does.

2023-10-01 20:49 UTC, msalauyou requested changes
@rila19, I am very satisfied with your PR. Code looks good. Please see some of my comments. And I don't see the answers on theoretical questions, I remember you had it in your read me file, please add it as well.

2023-10-07 14:29 UTC, msalauyou approved these changes
@rila19 nice work! Thank you!
The code have some format issues, please don't forget to formatt it by pressing Ctrl + Alt + L :)

2023-10-07 14:29 UTC, msalauyou commented on String/Aufgabe3MonthAsString.java
> +    public static void main(String[] args) {
Fixed

2023-10-07 14:30 UTC, msalauyou commented on String/Aufgabe4Anagram.java
> +    public static boolean isAnagram(){
Fixed

2023-10-07 14:30 UTC, msalauyou commented on String/Aufgabe5Palindrom.java
> +    public static  void splitStringInArray(){
Fixed

2023-10-07 14:30 UTC, msalauyou commented on String/AufgabeE.java
> +    public static String Sprint9_Aufgabe(){
Fixed

2023-10-09 17:50 UTC, rila19 commented
Merge PR

2023-10-09 17:51 UTC, rila19 commented
Close

2023-10-09 17:51 UTC, closed without merging